export const BASE_URL = "";

export const FETCH_CLASSES_START = "FETCH_CLASSES_START";
export const FETCH_CLASSES_SUCCESS = "FETCH_CLASSES_SUCCESS";
export const FETCH_CLASSES_FAILURE = "FETCH_CLASSES_FAILURE";
export const ADD_CLASS_START = "ADD_CLASS_START";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_FAILURE = "ADD_CLASS_FAILURE";
export const REMOVE_CLASS_START = "REMOVE_CLASS_START";
export const REMOVE_CLASS_SUCCESS = "REMOVE_CLASS_SUCCESS";
export const REMOVE_CLASS_FAILURE = "REMOVE_CLASS_FAILURE";
export const EDIT_CLASS_START = "EDIT_CLASS_START";
export const EDIT_CLASS_SUCCESS = "EDIT_CLASS_SUCCESS";
export const EDIT_CLASS_FAILURE = "EDIT_CLASS_FAILURE";

export const FILTER_CLASSES = "FILTER_CLASSES";
export const SET_ATTENDING_START = "SET_ATTENDING_START";
export const SET_ATTENDING_SUCCESS = "SET_ATTENDING_SUCCESS";
export const SET_ATTENDING_FAILURE = "SET_ATTENDING_FAILURE";
